version: "3"

services:
  # ===================================================
  # NATS Server
  # ===================================================
  nats-server:
    image: nats:latest

  # ===================================================
  # Client Gateway
  # ===================================================
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223

  # ===================================================
  # Auth Microservice
  # ===================================================
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}

  # ===================================================
  # Products Microservice
  # ===================================================
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms
    volumes:
      - products-db:/usr/src/app/prisma # 👈 persiste el archivo .db
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223
      - DATABASE_URL=file:/usr/src/app/prisma/dev.db # 👈 ruta absoluta

  # # ===================================================
  # # Orders Microservice
  # # ===================================================
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDER_DB_URL=${ORDER_DB_URL}
    image: orders-ms
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223
      - DATABASE_URL=${ORDER_DB_URL}

  # ===================================================
  # Payments Microservice
  # ===================================================
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222,nats://nats-server:4223
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
volumes:
  products-db:
